// SPDX-License-Identifier: Apache-2.0
/// The one place this executable's own build is read, plus the pure rendering over it.
///
/// `CurrentBuildConfiguration` is deliberately NOT inline: the macros below are a property of
/// the translation unit that tests them, so testing them here -- in a unit compiled into
/// `fastcache-bench` with `fastcache-bench`'s flags -- is what makes the answer a statement
/// about this binary. An inline function in a header would be instantiated in every including
/// unit and the linker would keep one of them, which is a different question.
///
/// Everything else here is pure: it takes a `BuildConfiguration` and returns text, so
/// `BuildBanner_test.cpp` can stage a build this host cannot produce.

#include "BuildBanner.hpp"

#include <FastCache/Core/EnumTable.hpp>

#include <algorithm>
#include <array>
#include <cstddef>
#include <format>
#include <ranges>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace FastCache::Bench
{

namespace
{

    // ---------------------------------------------------------------------------
    // One `#if` block per `BuildFact` row, in enumerator order.
    //
    // A macro cannot be tested from data -- `#if defined(X)` cannot be generated by a macro
    // expansion -- so this is the one place in the program that repeats per fact, and the
    // repetition is the point: each block names exactly one macro, in one spelling, and a reader
    // can check it against the compiler's documentation without following a table.
    //
    // What keeps the two tables in step is `StatedHereTable` below: it is an
    // `EnumTable<BuildFact, ...>`, so its extent comes from the enum, and `RowsInEnumeratorOrder`
    // refuses the BUILD when a fact was added to `BuildFactTable` and forgotten here -- the
    // missing row is value-initialized, claims enumerator 0 and does not sit at index 0.
    //
    // `__has_feature` is clang's and, since GCC 14, gcc's; MSVC does not have it, so every use is
    // guarded. Measured on clang 22.1.2, gcc 14.3.0, clang-cl 22.1.3 and cl (VS 18): gcc and
    // clang define `__SANITIZE_ADDRESS__`/`__SANITIZE_THREAD__` as well as answering
    // `__has_feature`, neither defines anything for UBSan, and `cl` defines
    // `__SANITIZE_ADDRESS__` under `/fsanitize=address`.
    // ---------------------------------------------------------------------------

#if defined(NDEBUG)
    constexpr bool NdebugStated = true;
#else
    constexpr bool NdebugStated = false;
#endif

#if defined(__OPTIMIZE__)
    constexpr bool OptimizeStated = true;
#else
    constexpr bool OptimizeStated = false;
#endif

#if defined(__OPTIMIZE_SIZE__)
    constexpr bool OptimizeSizeStated = true;
#else
    constexpr bool OptimizeSizeStated = false;
#endif

#if defined(__NO_INLINE__)
    constexpr bool NoInlineStated = true;
#else
    constexpr bool NoInlineStated = false;
#endif

#if defined(_DEBUG)
    constexpr bool MsvcDebugRuntimeStated = true;
#else
    constexpr bool MsvcDebugRuntimeStated = false;
#endif

#if defined(__MSVC_RUNTIME_CHECKS)
    constexpr bool MsvcRuntimeChecksStated = true;
#else
    constexpr bool MsvcRuntimeChecksStated = false;
#endif

#if defined(_GLIBCXX_ASSERTIONS)
    constexpr bool LibstdcxxAssertionsStated = true;
#else
    constexpr bool LibstdcxxAssertionsStated = false;
#endif

#if defined(_GLIBCXX_DEBUG)
    constexpr bool LibstdcxxDebugStated = true;
#else
    constexpr bool LibstdcxxDebugStated = false;
#endif

#if defined(__SANITIZE_ADDRESS__)
    constexpr bool AddressSanitizerStated = true;
#elif defined(__has_feature)
    #if __has_feature(address_sanitizer)
    constexpr bool AddressSanitizerStated = true;
    #else
    constexpr bool AddressSanitizerStated = false;
    #endif
#else
    constexpr bool AddressSanitizerStated = false;
#endif

#if defined(__SANITIZE_THREAD__)
    constexpr bool ThreadSanitizerStated = true;
#elif defined(__has_feature)
    #if __has_feature(thread_sanitizer)
    constexpr bool ThreadSanitizerStated = true;
    #else
    constexpr bool ThreadSanitizerStated = false;
    #endif
#else
    constexpr bool ThreadSanitizerStated = false;
#endif

#if defined(__has_feature)
    #if __has_feature(memory_sanitizer)
    constexpr bool MemorySanitizerStated = true;
    #else
    constexpr bool MemorySanitizerStated = false;
    #endif
#else
    constexpr bool MemorySanitizerStated = false;
#endif

#if defined(__has_feature)
    #if __has_feature(undefined_behavior_sanitizer)
    constexpr bool UndefinedBehaviorSanitizerStated = true;
    #else
    constexpr bool UndefinedBehaviorSanitizerStated = false;
    #endif
#else
    constexpr bool UndefinedBehaviorSanitizerStated = false;
#endif

// Whether the absence of `__OPTIMIZE__` means anything here. gcc, clang and clang-cl all
// define it from `-O1`/`/O1` upwards; `cl` defines no optimiser macro at all, so on `cl` an
// absent `__OPTIMIZE__` is not evidence of anything. Measured per driver rather than assumed:
// clang-cl defines `__clang__` and NOT `__GNUC__`, which is why both are named.
#if defined(__clang__) || defined(__GNUC__)
    constexpr OptimiserEvidence EvidenceHere = OptimiserEvidence::Stated;
#else
    constexpr OptimiserEvidence EvidenceHere = OptimiserEvidence::NotStatedByThisCompiler;
#endif

// What the build system was ASKED for. A label; see the header on why no verdict reads it.
#if defined(FASTCACHE_BENCH_BUILD_TYPE)
    constexpr std::string_view BuildTypeLabelHere = FASTCACHE_BENCH_BUILD_TYPE;
#else
    constexpr std::string_view BuildTypeLabelHere = "";
#endif

    /// Whether this translation unit's compiler stated one fact.
    struct StatedHere
    {
        BuildFact fact; ///< The fact.
        bool stated;    ///< Whether its macro is defined here.
    };

    /// One row per `BuildFact`, in enumerator order, reading the blocks above.
    constexpr EnumTable<BuildFact, StatedHere> StatedHereTable { {
        { .fact = BuildFact::AssertsCompiledOut, .stated = NdebugStated },
        { .fact = BuildFact::OptimiserRan, .stated = OptimizeStated },
        { .fact = BuildFact::OptimisedForSize, .stated = OptimizeSizeStated },
        { .fact = BuildFact::InliningOff, .stated = NoInlineStated },
        { .fact = BuildFact::MsvcDebugRuntime, .stated = MsvcDebugRuntimeStated },
        { .fact = BuildFact::MsvcRuntimeChecks, .stated = MsvcRuntimeChecksStated },
        { .fact = BuildFact::LibstdcxxAssertions, .stated = LibstdcxxAssertionsStated },
        { .fact = BuildFact::LibstdcxxDebugMode, .stated = LibstdcxxDebugStated },
        { .fact = BuildFact::AddressSanitizer, .stated = AddressSanitizerStated },
        { .fact = BuildFact::ThreadSanitizer, .stated = ThreadSanitizerStated },
        { .fact = BuildFact::MemorySanitizer, .stated = MemorySanitizerStated },
        { .fact = BuildFact::UndefinedBehaviorSanitizer, .stated = UndefinedBehaviorSanitizerStated },
    } };

    static_assert(RowsInEnumeratorOrder(StatedHereTable, &StatedHere::fact),
                  "every BuildFact needs a `#if` block above and a row here, at its own index -- a fact added to "
                  "BuildFactTable and forgotten here would otherwise read as never stated");

    /// The compiler's own identification of itself.
    /// @return A short name and the version the compiler states, never a CMake variable.
    [[nodiscard]] constexpr std::string_view CompilerHere() noexcept
    {
#if defined(__clang__) && defined(_MSC_VER)
        return "clang-cl " __clang_version__;
#elif defined(__clang__)
        return "clang " __clang_version__;
#elif defined(__GNUC__)
        return "gcc " __VERSION__;
#elif defined(_MSC_FULL_VER)
        // `_MSC_FULL_VER` is a number, and a number is not a string literal until it is
        // stringized twice: the inner expansion turns the macro into its digits.
    #define FASTCACHE_BENCH_STRINGIZE_INNER(x) #x
    #define FASTCACHE_BENCH_STRINGIZE(x)       FASTCACHE_BENCH_STRINGIZE_INNER(x)
        return "MSVC " FASTCACHE_BENCH_STRINGIZE(_MSC_FULL_VER);
    #undef FASTCACHE_BENCH_STRINGIZE
    #undef FASTCACHE_BENCH_STRINGIZE_INNER
#else
        return "unknown compiler (it states no version macro this build knows)";
#endif
    }

    /// One row of `AssertsTable`.
    struct AssertsRow
    {
        Asserts asserts;       ///< The state this row describes.
        std::string_view text; ///< How the banner prints it.
    };

    /// One row per `Asserts`, in enumerator order.
    constexpr EnumTable<Asserts, AssertsRow> AssertsTable { {
        { .asserts = Asserts::Live, .text = "LIVE -- NDEBUG is not defined, so assert() runs inside every measured body" },
        { .asserts = Asserts::CompiledOut, .text = "compiled out -- NDEBUG is defined" },
    } };

    static_assert(RowsInEnumeratorOrder(AssertsTable, &AssertsRow::asserts),
                  "every Asserts needs a row of AssertsTable, at its own index");

    /// One row of `OptimiserTable`.
    struct OptimiserRow
    {
        Optimiser optimiser;   ///< The state this row describes.
        std::string_view text; ///< How the banner prints it.
    };

    /// One row per `Optimiser`, in enumerator order.
    constexpr EnumTable<Optimiser, OptimiserRow> OptimiserTable { {
        { .optimiser = Optimiser::Ran, .text = "ran -- __OPTIMIZE__ is defined" },
        { .optimiser = Optimiser::DidNotRun,
          .text = "did NOT run -- this compiler defines __OPTIMIZE__ when it optimises and did not define it" },
        { .optimiser = Optimiser::Unstated,
          .text = "unknown -- this compiler states no optimiser macro, so nothing inside the binary can confirm it" },
    } };

    static_assert(RowsInEnumeratorOrder(OptimiserTable, &OptimiserRow::optimiser),
                  "every Optimiser needs a row of OptimiserTable, at its own index");

    /// How wide the rule lines around the verdict are.
    constexpr std::size_t VerdictRuleWidth = 100;

    /// Which column carries the per-operation cost, said once so every line that needs it agrees.
    constexpr std::string_view FigureColumnNote =
        "the per-operation cost is the `mean`, on the line BELOW the case name. `est run time`, beside the name, is "
        "samples x iterations over the whole benchmark and is NOT a per-operation cost";

    /// Every stated fact of @p reading, rendered as `macro (meaning)` and comma-separated.
    /// @param reading The configuration to read.
    /// @return The list, or a sentence saying there were none.
    [[nodiscard]] std::string RenderStatedFacts(BuildConfiguration const& reading)
    {
        std::string rendered;
        for (BuildFact const fact: reading.stated)
        {
            BuildFactRow const& row = BuildFactTable[static_cast<std::size_t>(fact)];
            if (!rendered.empty())
                rendered += ", ";
            rendered += std::format("{} ({})", row.macro, row.meaning);
        }
        if (rendered.empty())
            return "none";
        return rendered;
    }

} // namespace

bool Stated(BuildConfiguration const& reading, BuildFact fact)
{
    return std::ranges::find(reading.stated, fact) != std::ranges::end(reading.stated);
}

bool StatedAnyOfKind(BuildConfiguration const& reading, FactKind kind)
{
    return std::ranges::any_of(reading.stated, [kind](BuildFact const fact) {
        return BuildFactTable[static_cast<std::size_t>(fact)].kind == kind;
    });
}

Asserts AssertsOf(BuildConfiguration const& reading)
{
    return Stated(reading, BuildFact::AssertsCompiledOut) ? Asserts::CompiledOut : Asserts::Live;
}

Optimiser OptimiserOf(BuildConfiguration const& reading)
{
    if (Stated(reading, BuildFact::OptimiserRan))
        return Optimiser::Ran;
    // `/RTC` is incompatible with `/O`, so `cl` stating it settles the question its missing
    // optimiser macro cannot. Measured: `cl /Od /RTC1` defines `__MSVC_RUNTIME_CHECKS` and
    // `cl /O2` does not, while clang-cl defines it under no flags at all.
    if (Stated(reading, BuildFact::MsvcRuntimeChecks))
        return Optimiser::DidNotRun;
    if (reading.optimiserEvidence == OptimiserEvidence::Stated)
        return Optimiser::DidNotRun;
    return Optimiser::Unstated;
}

StandingReason ReasonFor(BuildConfiguration const& reading)
{
    for (StandingRow const& row: StandingTable)
        if (row.holds(reading))
            return row.reason;
    // Unreachable: `StandingReason::Confirmed`'s predicate is always true, and
    // `RowsInEnumeratorOrder` above proves that row is present. Named rather than asserted,
    // because a `Confirmed` answer here would be the one arm no reading produced.
    return StandingReason::Confirmed;
}

Standing StandingFor(StandingReason reason)
{
    return StandingTable[static_cast<std::size_t>(reason)].standing;
}

std::span<BannerLine const> BannerLines()
{
    static constexpr auto lines = std::to_array<BannerLine>({
        { .label = "build type (as configured -- a LABEL, never evidence)",
          .read =
              +[](BuildConfiguration const& reading) {
                  return reading.buildTypeLabel.empty()
                             ? std::string { "(not set -- the generator resolves it at build time)" }
                             : std::string { reading.buildTypeLabel };
              } },
        { .label = "compiler (as it identifies itself)",
          .read = +[](BuildConfiguration const& reading) { return std::string { reading.compiler }; } },
        { .label = "asserts",
          .read =
              +[](BuildConfiguration const& reading) {
                  return std::string { AssertsTable[static_cast<std::size_t>(AssertsOf(reading))].text };
              } },
        { .label = "optimiser",
          .read =
              +[](BuildConfiguration const& reading) {
                  return std::string { OptimiserTable[static_cast<std::size_t>(OptimiserOf(reading))].text };
              } },
        { .label = "macros this compiler stated",
          .read = +[](BuildConfiguration const& reading) { return RenderStatedFacts(reading); } },
    });
    return lines;
}

std::string RenderVerdict(BuildConfiguration const& reading)
{
    StandingReason const reason = ReasonFor(reading);
    MarkerRow const& marker = MarkerTable[static_cast<std::size_t>(StandingFor(reason))];
    std::string const rule(VerdictRuleWidth, marker.emphasis);

    return std::format("{}\n{} these figures are {} -- {}\n{}\n",
                       rule,
                       std::string(3, marker.emphasis),
                       marker.marker,
                       StandingTable[static_cast<std::size_t>(reason)].sentence,
                       rule);
}

std::string RenderBuildBanner(BuildConfiguration const& reading)
{
    // The two-space indent is the banner's shape contract: an indented `  label: value`
    // line is a FACT about this build, and nothing else is. `bench/inproc_bench.py` reads
    // those lines back into its report's environment block, so the column note below is
    // deliberately flush-left -- it is an instruction to the reader, not a property of the
    // binary, and a report that recorded it as one would be describing its own prose.
    std::string banner = "fastcache-bench: the build these figures come from\n";
    for (BannerLine const& line: BannerLines())
        banner += std::format("  {}: {}\n", line.label, line.read(reading));
    banner += std::format("reading a figure: {}\n", FigureColumnNote);
    banner += RenderVerdict(reading);
    return banner;
}

std::string RenderFigure(Figure const& figure, StandingReason reason)
{
    MarkerRow const& marker = MarkerTable[static_cast<std::size_t>(StandingFor(reason))];
    return std::format("fastcache-bench figure [{}]: {}: mean = {:.2f} ns/op over {} sample(s); est run time "
                       "{:.2f} ns is the whole benchmark and not the cost\n",
                       marker.marker,
                       figure.name,
                       figure.meanNanoseconds,
                       figure.samples,
                       figure.estimatedNanoseconds);
}

BuildConfiguration CurrentBuildConfiguration()
{
    std::vector<BuildFact> stated;
    for (StatedHere const& row: StatedHereTable)
        if (row.stated)
            stated.push_back(row.fact);

    return BuildConfiguration { .buildTypeLabel = BuildTypeLabelHere,
                                .compiler = CompilerHere(),
                                .stated = std::move(stated),
                                .optimiserEvidence = EvidenceHere };
}

} // namespace FastCache::Bench
